

services:
  mongo:
    image: mongo
    container_name: opencart-mongo-dev
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: opencart-backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: opencart-frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mongo-data:
